# Generated by Django 2.0.1 on 2018-01-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mailgun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailgun',
            name='incoming',
        ),
    ]
