# Generated by Django 2.0.4 on 2018-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pgpkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
