# Generated by Django 2.0.4 on 2018-05-02 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pgpkey_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='finger_print',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
