# Generated by Django 2.0.4 on 2018-05-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180502_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='finger_print',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
