# Generated by Django 2.0.4 on 2018-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180504_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='passphrase',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
