# Generated by Django 2.0.7 on 2018-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pgpkey_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgun',
            name='encryption',
            field=models.BooleanField(default=True),
        ),
    ]
