# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.EmailField(max_length=254)),
                ('to', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='')),
                ('message_id', models.CharField(max_length=500)),
                ('cc', models.EmailField(default='', max_length=254)),
                ('bcc', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('incoming', 'Inbox'), ('outgoing', 'Sent'), ('draft', 'Draft')], max_length=5)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadedView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain')),
                ('message', models.ManyToManyField(to='mail.Message')),
            ],
        ),
        migrations.CreateModel(
            name='UrlKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailgun_key', models.CharField(max_length=500)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain'),
        ),
    ]
