# Generated by Django 2.0.1 on 2018-01-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_mailgun_incoming'),
        ('mail', '0002_auto_20180117_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MailGun'),
        ),
    ]
