# Generated by Django 2.0.1 on 2018-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='message_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
