# Generated by Django 2.0.1 on 2018-01-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
