# Generated by Django 2.0.1 on 2018-01-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20180118_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='file_obj',
        ),
    ]
