# Generated by Django 2.0.1 on 2018-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_auto_20180122_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_read',
        ),
        migrations.AddField(
            model_name='thread',
            name='mails',
            field=models.ManyToManyField(to='mail.Mail'),
        ),
    ]
