# Generated by Django 2.0.1 on 2018-01-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='sane_body',
        ),
    ]
