# Generated by Django 2.0.1 on 2018-02-01 06:01

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_remove_mail_sane_body'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='thread',
            name='mails',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='mail.Mail'),
        ),
    ]
