# Generated by Django 2.0.2 on 2018-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_auto_20180201_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='in_reply_to',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
