# Generated by Django 2.0.4 on 2018-05-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_mail_in_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='state',
            field=models.CharField(choices=[('Q', 'Queue'), ('S', 'Success'), ('D', 'Draft'), ('R', 'Received'), ('T', 'Trash'), ('F', 'Failed')], max_length=1),
        ),
    ]
