# Generated by Django 2.0.4 on 2018-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_auto_20180505_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='m_type',
            field=models.CharField(choices=[('F', 'From'), ('T', 'To'), ('B', 'Blocked')], max_length=1),
        ),
    ]
