# Generated by Django 2.0.7 on 2018-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_auto_20180514_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='encryption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='encryption',
            field=models.BooleanField(default=True),
        ),
    ]
